config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :days
  root 'days#index'
  get '/about', to: "static#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :user
  validates :gift, presence: true, length: {minimum: 20}
  validates :thing, presence: true, length: {minimum: 20}
  validates :thing, presence: true, length: {minimum: 20}
  validates :daily, presence: true, length: {minimum: 20}
  validates :effort, presence: true, length: {minimum: 20}
  validates :improvement, presence: true, length: {minimum: 20}

  def self.stub
  	"hello world"
  end
end

app/models/motivator.rb
class Motivator < ApplicationRecord
	def self.quoteget
	  num = rand(1-99)
	  Motivator.find(num)
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :days
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
  before_action :authenticate_user!
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]
  before_action :quote, only: [:new, :index]

  # GET /days
  # GET /days.json
  def index
    @days = Day.where(user_id: current_user.id).order(:created_at).limit(10)
  end

  # GET /days/1
  # GET /days/1.json
  def show
  end

  # GET /days/new
  def new
    @day = current_user.days.build
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = current_user.days.build(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
      else
        quote
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url, notice: 'Day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
      if @day.user_id != current_user.id
        redirect_to root_path
      end
    end

    def quote
      @quote = Motivator.quoteget
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:gift, :thing, :daily, :effort, :improvement)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/days/_form.html.erb
  
<%= form_with(model: day, local: true) do |form| %>
  <% if day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="columns">
  <div class="column is-three-fifths is-offset-one-fifth">
  <div class="field">
    <%= form.label :gift %>
    <%= form.text_area :gift, class: "input is-primary" %>
  </div>

  <div class="field">
  <div class="control">
    <%= form.label :thing %>
    <%= form.text_area :thing, class: "input is-primary" %>
  </div>
</div>

  <div class="field">
    <div class="control">
    <%= form.label :daily %>
    <%= form.text_area :daily %>
  </div>
</div>

  <div class="field">
    <%= form.label :effort %>
    <%= form.text_area :effort %>
  </div>

  <div class="field">
    <%= form.label :improvement %>
    <%= form.text_area :improvement %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-primary" %>
  </div>
<% end %>
</div>
</div>

app/views/days/edit.html.erb
<h1>Editing Day</h1>

<%= render 'form', day: @day %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>
<%= link_to 'Delete', day_path(@day), method: :delete %>

app/views/days/index.html.erb
<div class='container'>
<div class='content'>
<h1>Index of days</h1>
<%= @quote.quote %>
<table>
  <thead>
    <tr>
      <th>Gift</th>
      <th>Thing</th>
      <th>Daily</th>
     
    </tr>
  </thead>

  <tbody>
    <% @days.each do |day| %>
      <tr>
        <td><%= link_to day.created_at.strftime("%d %m %y"), day %></td>
        <td><%= day.gift %></td>
        <td><%= day.thing %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Day', new_day_path, class: "button is-primary" %>
</div>
</div>

app/views/days/new.html.erb
<div class="container">
  <div class="content">

<h1>New Day</h1>
<%= @quote.quote %>
<%= render 'form', day: @day %>
</div>
</div>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class='column is-11 is-offset-1'>
<div class="content ">
  <h1>Diary entry from <%= @day.created_at.strftime("%D") %> </h1>
<p>
  <strong>TH:</strong>
  <%= @day.gift %>
</p>

<p>
  <strong>Thing:</strong>
  <%= @day.thing %>
</p>

<p>
  <strong>Daily:</strong>
  <%= @day.daily %>
</p>

<p>
  <strong>Effort:</strong>
  <%= @day.effort %>
</p>

<p>
  <strong>Improvement:</strong>
  <%= @day.improvement %>
</p>

<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', days_path %>
</div>
</div>
</div>

app/views/layouts/_alert.html.erb
<div class="container">
<% if flash[:notice] %>
    <div class="notification is-info"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:alert] %>
    <div class="notification is-info"><%= flash[:alert] %></div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-transparent">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
    </a>
    <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
      <span></span>
      <span></span>
      <span></span>
    </div>
  </div>

  <div id="navbarExampleTransparentExample" class="navbar-menu">
    <div class="navbar-start">
     
        <%= link_to "Home", root_path, class: "navbar-item" %>
     
      <div class="navbar-item">
          <%= link_to "About", about_path %>
      
       
      </div>
    </div>

    <div class="navbar-end">
      <% if user_signed_in? %>
      <div class="navbar-item">
        <%= link_to "Log out", destroy_user_session_path, method: :delete %></div>
        <% else %>
        <%= link_to "Log in", new_user_session_path, class: "navbar-item" %>
        <%= link_to "Sign up", new_user_registration_path, class: "navbar-item" %>
        <% end %>
        
              
              
    
          
         
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Threemin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/alert' %>
    <%= yield %>
    </div>
  </body>
</html>